# Generated by Django 5.2 on 2025-04-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_landlord',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_support_engineer',
            new_name='is_tenant',
        ),
    ]
